// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/validator/validator.go

// Package interaction is a generated GoMock package.
package interaction

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockValidator is a mock of Validator interface.
type MockValidator struct {
	ctrl     *gomock.Controller
	recorder *MockValidatorMockRecorder
}

// MockValidatorMockRecorder is the mock recorder for MockValidator.
type MockValidatorMockRecorder struct {
	mock *MockValidator
}

// NewMockValidator creates a new mock instance.
func NewMockValidator(ctrl *gomock.Controller) *MockValidator {
	mock := &MockValidator{ctrl: ctrl}
	mock.recorder = &MockValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidator) EXPECT() *MockValidatorMockRecorder {
	return m.recorder
}

// CardNumberValidator mocks base method.
func (m *MockValidator) CardNumberValidator(cardNumber string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CardNumberValidator", cardNumber)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CardNumberValidator indicates an expected call of CardNumberValidator.
func (mr *MockValidatorMockRecorder) CardNumberValidator(cardNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CardNumberValidator", reflect.TypeOf((*MockValidator)(nil).CardNumberValidator), cardNumber)
}

// CardSchemaValidator mocks base method.
func (m *MockValidator) CardSchemaValidator(cardNumber string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CardSchemaValidator", cardNumber)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CardSchemaValidator indicates an expected call of CardSchemaValidator.
func (mr *MockValidatorMockRecorder) CardSchemaValidator(cardNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CardSchemaValidator", reflect.TypeOf((*MockValidator)(nil).CardSchemaValidator), cardNumber)
}
